apiVersion: v1
kind: ConfigMap
metadata:
  name: auditd-rules
  namespace: auditd-logging
  labels:
    app: auditd-customizations
data:
  auditd.sh: |
    # clear existing rules
    auditctl -D

    # File and Directory Discovery (ls)
    # snippet from https://github.com/deep-security/auditd-config/blob/master/audit.rules
    auditctl -w /usr/bin/ls -p x -k T1083_File_And_DIrectory_Discovery
    auditctl -w /usr/bin/dir -p x -k T1083_File_And_DIrectory_Discovery
    auditctl -w /usr/bin/tree -p x -k T1083_File_And_DIrectory_Discovery
    auditctl -w /usr/bin/find -p x -k T1083_File_And_DIrectory_Discovery
    auditctl -w /usr/bin/locate -p x -k T1083_File_And_DIrectory_Discovery
    auditctl -w /usr/bin/pwd -p x -k T1083_File_And_DIrectory_Discovery

    # lock auditd rules
    auditctl -e 2

